version: '3.8'

services:
  database:
    container_name: database
    restart: always
    build:
      context: ./database
      dockerfile: dockerfile
    environment:
      APP_LOAD_SAMPLES: true
      APP_USE_EXPERIMENTAL_SCRIPT: false
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    hostname: database
    networks:
      - internal
    # volumes:
    #   - database_volume:/var/lib/postgresql/data
  
  main_app:
    container_name: main_app
    hostname: main_app
    restart: always
    depends_on:
      - database
    build:
      context: ./main_app
      dockerfile: dockerfile
    networks:
      - internal
    environment:
      UVICORN_WEB_CONCURRENCY: 1
      UVICORN_CMD_OPTIONS: --reload
      APP_DEBUG_MODE: true
      APP_LOG_PATH: /app/logs/main_app
      APP_LOG_NAME: main_app
      APP_LOG_LAYER: 9999
      APP_STARTUP_DELAY: 5
      DB_HOST: database
      DB_PORTNO: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
  
  proxy:
    container_name: proxy
    restart: always
    depends_on:
      - database
      - main_app
    build:
      context: ./proxy
      dockerfile: dockerfile
    hostname: proxy
    networks:
      - internal
      - external
    ports:
      - 80:80

networks:
  internal: 
    driver: bridge
  external: 

volumes:
  database_volume: 