version: '3.8'

services:
  database:
    container_name: database
    restart: always
    build:
      context: ./database
      dockerfile: dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    hostname: database
    networks:
      - internal
    volumes:
      - database_volume:/var/lib/postgresql/data
  
  main_app:
    container_name: main_app
    restart: always
    depends_on:
      - database
    build:
      context: ./main_app
      dockerfile: dockerfile
    hostname: main_app
    networks:
      - internal
  
  proxy:
    container_name: proxy
    restart: always
    depends_on:
      - main_app
      - database
    build:
      context: ./proxy
      dockerfile: dockerfile
    hostname: proxy
    networks:
      - internal
      - external
    ports:
      - 80:80

networks:
  internal: 
    driver: bridge
  external: 

volumes:
  database_volume: {}