
version: '3.8'

services:
  app:
    container_name: "main_app"
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src/
    environment:
      - UVICORN_OPTIONS=--reload
      - WEB_CONCURRENCY=1