
version: '3.8'

services:
  app:
    container_name: "main_app"
    depends_on:
      - database
    build: 
      context: .
      dockerfile: dockerfile
    volumes:
      - ./main_app:/app/src/main_app
    networks:
      - test_net
    ports:
      - 5000:5000
    environment:
      - UVICORN_WEB_CONCURRENCY=1
      - UVICORN_CMD_OPTIONS=--reload
      - APP_DEBUG_MODE=true
      - APP_LOG_PATH=/app/logs/main_app
      - APP_LOG_NAME=main_app
      - APP_LOG_LAYER=9999
  
  database:
    container_name: database
    hostname: database
    restart: always
    build:
      context: ../database
      dockerfile: dockerfile
    networks:
      - test_net
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

networks:
  test_net:
    driver: bridge